INFO - Test started:readRawDataTest
INFO - Test finished: readRawDataTest
INFO - Test results: 
 execution time - 1398 ms; 
 tests number - 1; 
 failed tests number - 0; 
 ignored tests number - 0; 
 
INFO - Test started:readRawDataTest
ERROR - data\Present23.txt
java.nio.file.NoSuchFileException: data\Present23.txt
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.Files.newByteChannel(Unknown Source)
	at java.nio.file.Files.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
	at java.nio.file.Files.newInputStream(Unknown Source)
	at java.nio.file.Files.newBufferedReader(Unknown Source)
	at java.nio.file.Files.lines(Unknown Source)
	at java.nio.file.Files.lines(Unknown Source)
	at com.epam.second.reader.DataReader.readRawData(DataReader.java:19)
	at test.epam.second.reader.DataReaderTest.readRawDataTest(DataReaderTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at test.epam.second.testLogger.TestsRunner.run(TestsRunner.java:17)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
INFO - Test failed with the exception: java.lang.AssertionError: The total number of rows is wrong:  expected:<5> but was:<0>
INFO - Test finished: readRawDataTest
INFO - Test results: 
 execution time - 365 ms; 
 tests number - 1; 
 failed tests number - 1; 
 ignored tests number - 0; 
 
